Q1 - Mostrar informação sobre os alunos inscritos na academia "Iron Legs" após 11/01/2022 e que vivam na "Rua dos Fantasmas"

SELECT CC, PESSOA.NOME, SEXO, DATAINSCRICAO, FAIXA, RANKNACIONAL, ACADEMIA.NOME, MORADA.RUA
FROM PESSOA, ACADEMIA, MORADA
WHERE ACADEMIA.CODACADEMIA = PESSOA.CODACADEMIA AND
      MORADA.CODMORADA = PESSOA.CODMORADA AND
      UPPER(ACADEMIA.NOME) = UPPER("Iron Legs") AND
      TO_CHAR(PESSOA.DATAINSCRICAO, 'YYYY-MM-DD') > "2020-01-11" AND
      UPPER(MORADA.NOME) = UPPER('Rua dos Fantasmas') AND
      UPPER(CARGO) = UPPER('ALUNO')
ORDER BY PESSOA.NOME ASC;


Q2 - Mostrar a quantidade de alunos inscritos para cada academia
SELECT ACADEMIA.CODACADEMIA, ACADEMIA.NOME, COUNT(*) AS "Alunos Inscritos"
FROM PESSOA, ACADEMIA
WHERE ACADEMIA.CODACADEMIA = PESSOA.CODACADEMIA AND
      UPPER(CARGO) = UPPER('ALUNO')
GROUP BY ACADEMIA.NOME;


Q3 - Mostrar os professores que estejam classificados nos 10 melhores nacionais
SELECT CC, PESSOA.NOME, ACADEMIA.NOME RANKNACIONAL, FAIXA
FROM PESSOA, ACADEMIA
WHERE UPPER(CARGO) = UPPER('PROFESSOR') AND
      RANKNACIONAL <= 10 AND
      PESSOA.CODACADEMIA = ACADEMIA.CODACADEMIA
ORDER BY RANKNACIONAL ASC;


Q4 - Mostrar os equipamentos da academia "Dojo Fit" com preco inferior a 100€ da marca "Adidas"
SELECT EQUIPAMENTO.CODEQUIPAMENTO, MARCA.NOME, EQUIPAMENTO.MODELO, EQUIPAMENTO.PRECO
FROM MARCA, EQUIPAMENTO, ACADEMIA
WHERE ACADEMIA.CODACADEMIA = EQUIPAMENTO.CODACADEMIA AND
      EQUIPAMENTO.CODMARCA = MARCA.CODMARCA AND
      UPPER(ACADEMIA.NOME) = UPPER('Dojo Fit') AND
      EQUIPAMENTO.PRECO < 100 AND
      UPPER(MARCA.NOME) = UPPER('Adidas');


Q5 - Mostrar as academias com número de alunos superior à média
SELECT ACADEMIA.CODACADEMIA, ACADEMIA.NOME, COUNT(*) AS "Alunos Inscritos"
FROM PESSOA, ACADEMIA
WHERE ACADEMIA.CODACADEMIA = PESSOA.CODACADEMIA AND
      UPPER(CARGO) = UPPER('ALUNO')
GROUP BY ACADEMIA.NOME
HAVING COUNT(*) > (SELECT AVG(COUNT(*)) FROM PESSOA, ACADEMIA
                    WHERE ACADEMIA.CODACADEMIA = PESSOA.CODACADEMIA AND
                          UPPER(CARGO) = UPPER('ALUNO'));
ORDER BY ACADEMIA.NOME ASC;